import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { heightAt } from './worldgen';

// Shared golden vectors generated by the Rust server (apps/server/crates/sim `cargo test`).
// This pins TS worldgen bit-for-bit to the authoritative Rust worldgen so client and server
// never disagree on the terrain.
const golden: number[] = JSON.parse(
  readFileSync(fileURLToPath(new URL('./worldgen.golden.json', import.meta.url)), 'utf8'),
);

describe('worldgen parity with the Rust server (golden vectors)', () => {
  it('matches the shared golden heights', () => {
    // Same coordinate order the Rust generator uses: for i in 0..32 { for j in 0..32 }.
    const heights: number[] = [];
    for (let i = 0; i < 32; i++) {
      for (let j = 0; j < 32; j++) {
        heights.push(heightAt(i * 271, j * 409));
      }
    }
    expect(heights).toEqual(golden);
  });
});
